Some corrections

diff --git a/archroot/archroot b/archroot/archroot
--- a/archroot/archroot
+++ b/archroot/archroot
@@ -20,24 +20,15 @@ else
 fi
 
 checkdep() { command -v $1 > /dev/null 2>&1 || err "$1 is not installed. Please install it first!"; }
-err() { echo -e "\033[1;31m==> Error:\033[0m $@" && exit 1; }
-msg() { echo -e "\033[1;32m==>\033[0m $@"; }
+err() { echo -e "\e[1;31m==> Error:\e[0m $@" && exit 1; }
+msg() { echo -e "\e[1;32m==>\e[0m $@"; }
 asroot() { [[ $EUID -ne 0 ]] && err "Run this as root!"; }
 copyresolv() { $PRIV $INSTALL_PATH/copyresolv; }
-rd_msg() { echo -e "\033[1;31m==> Chroot API filesystems:\033[0m $@"; }
-gr_msg() { echo -e "\033[1;32m==> Chroot API filesystems:\033[0m $@"; }
-
-msg_mnt() {
-    echo -e "\033[1;32m*\033[0m $@" "\033[1;32m[\033[0m  Mounted\033[1;32m  ]\033[0m"
-}
-
-msg_mnt_rt() {
-    echo -e "\033[1;32m*\033[0m $@" "\033[1;32m[\033[0m  Runtime\033[1;32m  ]\033[0m"
-}
-
-msg_umnt() {
-    echo -e "\033[1;31m*\033[0m $@" "\033[1;31m[\033[0m Unmounted\033[1;31m ]\033[0m"
-}
+rd_msg() { echo -e "\e[1;31m==> Chroot API filesystems:\e[0m $@"; }
+gr_msg() { echo -e "\e[1;32m==> Chroot API filesystems:\e[0m $@"; }
+msg_mnt() { echo -e "\e[1;32m*\e[0m $@" "\e[1;32m[\e[0m  Mounted\e[1;32m  ]\e[0m"; }
+msg_mnt_rt() { echo -e "\e[1;32m*\e[0m $@" "\e[1;32m[\e[0m  Runtime\e[1;32m  ]\e[0m"; }
+msg_umnt() { echo -e "\e[1;31m*\e[0m $@" "\e[1;31m[\e[0m Unmounted\e[1;31m ]\e[0m"; }
 
 storeenv() {
     echo "$DBUS_SESSION_BUS_ADDRESS" > /tmp/archroot_dbus_session_address
@@ -46,7 +37,7 @@ storeenv() {
 
 help_text() {
 cat << EOF
-USAGE: archroot OPTIONS
+USAGE: archroot <OPTIONS>
 
 OPTIONS:
   -c, --create URL      Creates a chroot environment.
@@ -173,7 +164,7 @@ case $1 in
             mkdir -p $CHROOT/lib/modules
             mkdir -p $CHROOT/var/lib/dbus
             mnt_apifs
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
             echo "$USER" > /tmp/archroot_localuser
             cp $INSTALL_PATH/archsetup $CHROOT/archsetup
             cp /etc/machine-id $CHROOT/etc/machine-id
@@ -186,21 +177,21 @@ case $1 in
     ;;
     -m|--mount)
         if mount | grep -E "$CHROOT/dev|$CHROOT/home|$CHROOT/usr/lib/modules|$CHROOT/proc|$CHROOT/run|$CHROOT/sys|$CHROOT/tmp|$CHROOT/var/lib/dbus" > /dev/null; then
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
         else
             gr_msg "Mounting..."
             mnt_apifs
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
         fi
     ;;
     -u|--unmount)
         if mount | grep -E "$CHROOT/dev|$CHROOT/home|$CHROOT/usr/lib/modules|$CHROOT/proc|$CHROOT/run|$CHROOT/sys|$CHROOT/tmp|$CHROOT/var/lib/dbus" > /dev/null; then
             gr_msg "Unmounting..."
             umnt_apifs
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
             gr_msg "If failed to unmount simply try again or reboot host system!"
         else
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
         fi
     ;;
     -r|--remount-run)
@@ -209,29 +200,29 @@ case $1 in
                 gr_msg "Remounting /run ..."
                 $umount $Lvar $CHROOT/run
                 $mount $Rvar /run $CHROOT/run 2> /dev/null
-                $(command -v archroot) -s 2> /dev/null
+                $(command -v "archroot") -s 2> /dev/null
                 gr_msg "/run remounted successfuly"
             else
-                $(command -v archroot) -s 2> /dev/null
+                $(command -v "archroot") -s 2> /dev/null
                 rd_msg "Failed to remount /run"
             fi
         else
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
             gr_msg "Please mount chroot API filesystems before remount /run !"
             rd_msg "Failed to remount /run"
         fi
     ;;
     --runtime-only)
         if mount | grep -E "$CHROOT/dev|$CHROOT/home|$CHROOT/usr/lib/modules|$CHROOT/proc|$CHROOT/run|$CHROOT/sys|$CHROOT/tmp|$CHROOT/var/lib/dbus" > /dev/null; then
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
             gr_msg "Mounting $XDG_RUNTIME_DIR only..."
             [[ ! -e $CHROOT$(cat /tmp/archroot_xdg_runtime_dir 2> /dev/null) ]] && $PRIV mkdir -p $CHROOT$(cat /tmp/archroot_xdg_runtime_dir 2> /dev/null)
             $umount $Rvar $CHROOT/run 2> /dev/null
             $umount $Lvar $CHROOT$(cat /tmp/archroot_xdg_runtime_dir 2> /dev/null) 2> /dev/null
             $mount $Rvar $(cat /tmp/archroot_xdg_runtime_dir 2> /dev/null) $CHROOT$(cat /tmp/archroot_xdg_runtime_dir 2> /dev/null)
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
         else
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
             gr_msg "Please mount chroot API filesystems before mounting $XDG_RUNTIME_DIR only!"
             rd_msg "Failed to mount $XDG_RUNTIME_DIR"
         fi
@@ -252,7 +243,7 @@ case $1 in
             $PRIV $INSTALL_PATH/copyresolv
             $PRIV $INSTALL_PATH/command enter
         else
-            $(command -v archroot) -s 2> /dev/null
+            $(command -v "archroot") -s 2> /dev/null
             gr_msg "Please mount chroot API filesystems before entering chroot environment!"
         fi
 	;;
diff --git a/archroot/archsetup b/archroot/archsetup
--- a/archroot/archsetup
+++ b/archroot/archsetup
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
-L_USER="$(cat /tmp/archroot_localuser)"
+L_USER="$(cat /tmp/archroot_localuser 2> /dev/null)"
 
-err() { echo -e "\033[1;31m==> Error:\033[0m $@" && exit 1; }
-msg() { echo -e "\033[1;32m==> $@ \033[0m"; }
+err() { echo -e "\e[1;31m==> Error:\e[0m $@" && exit 1; }
+msg() { echo -e "\e[1;32m==> $@ \e[0m"; }
 
 msg "Initializing pacman keyrings..."
 pacman-key --init
@@ -40,6 +40,7 @@ echo "Enter new password for $L_USER"
 while true; do
 	passwd $L_USER && break
 done
+
 sed -i 's_# %wheel ALL=(ALL) NOPASSWD: ALL_%wheel ALL=(ALL) NOPASSWD: ALL_' /etc/sudoers
 touch /etc/archroot
 
